Rails.application.routes.draw do
  get 'readers/index'
  get 'readers/show'
  get 'readers/new'
  get 'readers/create'
  get 'readers/edit'
  get 'readers/update'
  get 'readers/destroy'
  get 'tags/index'
  get 'tags/show'
  get 'tags/new'
  get 'tags/create'
  get 'tags/edit'
  get 'tags/update'
  get 'tags/destroy'
  get 'articles/index'
  get 'articles/show'
  get 'articles/new'
  get 'articles/create'
  get 'articles/edit'
  get 'articles/update'
  get 'articles/destroy'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
